AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  myDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: tabmine
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CreateItemFunction/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /writedb
            Method: post
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref myDB

  RetrieveItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RetrieveItemsFunction/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /readdb
            Method: post
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref myDB
