AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        TABLE_NAME: whiteBoard

Resources:
  whiteBoardDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: whiteBoard
      PrimaryKey:
        Name: itemId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CreateItemFunction/
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /writeRecord
            Method: post
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref whiteBoardDB

  RetrieveItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RetrieveItemsFunction/
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /readRecords
            Method: get
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref whiteBoardDB

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UpdateItemFunction/
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateRecord
            Method: get
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref whiteBoardDB
  
  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DeleteItemFunction/
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deleteRecord
            Method: get
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref whiteBoardDB
