name: CD

on:
  # TODO no secrets yet, so no automation for now
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Filter changed Lambda sources
  #       uses: dorny/paths-filter@v2.2.1
  #       id: filter
  #       with:
  #         filters: .github/filters.yml

  #     - name: Package and deploy
  #       uses: blombard/lambda-monorepo@master
  #       with:
  #         lambda-functions: '${{ toJson(steps.filter.outputs) }}'
  #         zip-params: '*.js *.json src/ node_modules/'
  #         alias-name: 'production'
  #         layer-name: 'MyLayer'

  deploy-ui:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm i

      - name: Build static app
        run: npm run build

      - name: Deploy 
        uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: falnyr/aws-sam-deploy-action@v1.2.1
        env:
          TEMPLATE: 'lambdas/template.yaml'
          AWS_STACK_NAME: whiteboard-api
          AWS_REGION: 'us-east-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
