name: Monorepo PR Repo Labeler

on: 
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - "lambdas/**"
      - "ui/**"

jobs:
  labelPR:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: adamzolyak/monorepo-pr-labeler-action@patching
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: 'sample_prefix' # optional
          suffix: 'sample_suffix' # optional